backend:
  name: git-gateway
  branch: main

media_folder: "images" # المجلد الذي تحفظ فيه الصور
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Page Accueil"
        name: "home"
        fields:
          - {label: "Titre", name: "hero_title", widget: "string"}
